services:
  geoipupdate:
    container_name: geoipupdate
    image: ghcr.io/maxmind/geoipupdate
    restart: unless-stopped
    env_file: .env
    environment:
      - 'GEOIPUPDATE_EDITION_IDS=GeoLite2-ASN GeoLite2-City GeoLite2-Country'
      - GEOIPUPDATE_FREQUENCY=72
    networks:
      - geoipupdate
    volumes:
      - './geoip_data:/usr/share/GeoIP'
    healthcheck:
      test: ['CMD', 'test', '-f', '/usr/share/GeoIP/GeoLite2-City.mmdb']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s

networks:
  geoipupdate:
